spring:
  datasource:
    url: jdbc:mysql://localhost:3306/overnight_db
    username: root
    password: root

  liquibase:
    change-log: classpath:/changelog/migration.xml

  mail:
    host: smtp.gmail.com
    username: poxospoxosyan1985@gmail.com
    password: tiqhyxcvmeiqiohe
    port: 587

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

overnight:
  images:
    folder: C:\\Users\\Hoso\\IdeaProjects\\modular\\overnight-parent\\overnight-web\\images

logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz # by date
      max-file-size: 10MB # by size
  file:
    name: C:\Users\Hoso\IdeaProjects\modular\overnight-parent\overnight-web\log\application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}  %-5level %logger{36} - %msg%n"
  level:
    root: info
    com.example: info


